import type { ThemeConfig } from '@/types/hero'

export const agencyTheme: ThemeConfig = {
  id: 'agency',
  name: 'Lumina Studio',
  tagline: 'Digital agency cinematic stage',
  layout: 'split',
  nav: {
    logo: 'LUMINA',
    links: ['Work', 'Method', 'Studio', 'Contact'],
    cta: 'Start a Project',
  },
  headline: {
    line1: 'Interfaces that',
    line2: 'feel inevitable',
    accent: 'feel inevitable',
  },
  subheadline:
    'A reusable cinematic system — website mockups, floating UI, and product depth tuned for every client brand.',
  buttons: [
    { label: 'View Case Studies', variant: 'primary' },
    { label: 'Book a Session', variant: 'secondary' },
  ],
  colors: {
    bgFrom: '#070B16',
    bgVia: '#141B33',
    bgTo: '#05070F',
    accent: '#7C5CFF',
    accentSoft: '#41D1FF',
    text: '#F4F6FF',
    textMuted: 'rgba(244, 246, 255, 0.66)',
    glow: 'rgba(124, 92, 255, 0.4)',
    vignette: 'rgba(2, 4, 12, 0.75)',
    particle: ['#7C5CFF', '#41D1FF', '#FFFFFF', '#B8A6FF'],
    smoke: 'rgba(180, 200, 255, 0.16)',
  },
  mockup: {
    title: 'Nova Dashboard',
    subtitle: 'Product analytics reimagined',
    browserUrl: 'lumina.studio/nova',
  },
  product: {
    src: '/assets/agency/analytics.svg',
    alt: 'Floating conversion analytics card',
    width: 280,
  },
  floatingObjects: [
    {
      id: 'ui-card',
      src: '/assets/agency/ui-card.svg',
      alt: 'Floating UI analytics card',
      x: 12,
      y: 26,
      width: 180,
      depth: 1.1,
      rotate: -8,
      floatDuration: 8.4,
      floatDelay: 0.3,
      floatAmplitude: 16,
      floatAmplitudeX: 8,
      floatRotate: 5,
      scrollSpeed: 1.4,
      zIndex: 40,
    },
    {
      id: 'code-chip',
      src: '/assets/agency/code-chip.svg',
      alt: 'Floating code chip',
      x: 74,
      y: 22,
      width: 170,
      depth: 1.05,
      rotate: 6,
      floatDuration: 7.1,
      floatDelay: 0.9,
      floatAmplitude: 18,
      floatAmplitudeX: 10,
      floatRotate: -6,
      scrollSpeed: 1.3,
      zIndex: 38,
      hideOnMobile: true,
    },
    {
      id: 'cursor',
      src: '/assets/agency/cursor.svg',
      alt: 'Cursor pointer',
      x: 68,
      y: 58,
      width: 54,
      depth: 1.45,
      rotate: 12,
      floatDuration: 5.2,
      floatDelay: 0.1,
      floatAmplitude: 22,
      floatAmplitudeX: 14,
      floatRotate: 10,
      scrollSpeed: 1.7,
      zIndex: 46,
    },
    {
      id: 'orb-1',
      src: '/assets/agency/glow-orb.svg',
      alt: 'Glow orb',
      x: 18,
      y: 66,
      width: 100,
      depth: 0.65,
      rotate: 0,
      floatDuration: 11.5,
      floatDelay: 1.4,
      floatAmplitude: 12,
      floatAmplitudeX: 6,
      floatRotate: 0,
      scrollSpeed: 0.75,
      zIndex: 28,
      hideOnTablet: true,
    },
    {
      id: 'orb-2',
      src: '/assets/agency/glow-orb.svg',
      alt: 'Glow orb',
      x: 82,
      y: 70,
      width: 70,
      depth: 0.9,
      rotate: 0,
      floatDuration: 9.8,
      floatDelay: 2,
      floatAmplitude: 14,
      floatAmplitudeX: 8,
      scrollSpeed: 1.1,
      zIndex: 32,
      hideOnMobile: true,
    },
    {
      id: 'ui-card-2',
      src: '/assets/agency/ui-card.svg',
      alt: 'Secondary UI card',
      x: 8,
      y: 48,
      width: 140,
      depth: 1.25,
      rotate: 10,
      floatDuration: 6.6,
      floatDelay: 1.7,
      floatAmplitude: 15,
      floatAmplitudeX: 9,
      floatRotate: -8,
      scrollSpeed: 1.5,
      zIndex: 42,
      hideOnTablet: true,
    },
  ],
  particles: {
    count: 32,
    colors: ['#7C5CFF', '#41D1FF', '#FFFFFF', '#B8A6FF'],
  },
  smoke: {
    enabled: true,
    color: 'rgba(180, 200, 255, 0.16)',
  },
}
