import type { ThemeConfig } from '@/types/hero'

export const coffeeTheme: ThemeConfig = {
  id: 'coffee',
  name: 'Aroma Atelier',
  tagline: 'A coffee website that feels warm before you even visit',
  layout: 'cinematic',
  nav: {
    logo: 'AROMA',
    links: ['Blend', 'Origin', 'Ritual', 'Journal'],
    cta: 'Order Reserve',
  },
  headline: {
    line1: 'Warm before',
    line2: 'the first sip',
    accent: 'the first sip',
  },
  subheadline:
    'Scroll-based parallax brings the cup to life — steam rises, milk flows, ice drops, sugar dissolves, beans float.',
  buttons: [
    { label: 'Taste the Ritual', variant: 'primary' },
    { label: 'Explore the Blend', variant: 'secondary' },
  ],
  colors: {
    bgFrom: '#140C08',
    bgVia: '#3B2418',
    bgTo: '#0C0806',
    accent: '#E8B07A',
    accentSoft: '#C4895A',
    text: '#F7EFE6',
    textMuted: 'rgba(247, 239, 230, 0.68)',
    glow: 'rgba(232, 176, 122, 0.42)',
    vignette: 'rgba(6, 3, 1, 0.78)',
    particle: ['#E8B07A', '#F3D5B5', '#FFFFFF', '#C4895A'],
    smoke: 'rgba(255, 236, 214, 0.3)',
  },
  mockup: {
    title: 'Morning Ritual',
    subtitle: 'Single-origin pour, crafted slow',
    browserUrl: 'aroma.atelier/ritual',
  },
  product: {
    // Drop your final cup PNG at public/assets/coffee/cup.png
    src: '/assets/coffee/cup.png',
    alt: 'Iced coffee with cream pour and splash',
    width: 420,
  },
  floatingObjects: [
    {
      id: 'splash-main',
      src: '/assets/coffee/splash.png',
      alt: 'Coffee splash',
      x: 58,
      y: 42,
      width: 520,
      depth: 1.45,
      rotate: -8,
      floatDuration: 7.5,
      floatDelay: 0.1,
      floatAmplitude: 12,
      floatAmplitudeX: 8,
      floatRotate: 4,
      scrollSpeed: 1.4,
      zIndex: 58,
      ritual: 'splash',
      blendMode: 'screen',
    },
    {
      id: 'splash-vertical',
      src: '/assets/coffee/splash-vertical.png',
      alt: 'Coffee splash burst',
      x: 36,
      y: 36,
      width: 280,
      depth: 1.25,
      rotate: 12,
      floatDuration: 8.8,
      floatDelay: 0.5,
      floatAmplitude: 14,
      floatAmplitudeX: 6,
      floatRotate: -5,
      scrollSpeed: 1.35,
      zIndex: 57,
      ritual: 'splash',
      blendMode: 'screen',
      hideOnMobile: true,
    },
    {
      id: 'bean-1',
      src: '/assets/coffee/bean.png',
      alt: 'Roasted coffee bean',
      x: 14,
      y: 30,
      width: 72,
      depth: 1.25,
      rotate: -24,
      floatDuration: 7.2,
      floatDelay: 0.15,
      floatAmplitude: 20,
      floatAmplitudeX: 12,
      floatRotate: 10,
      scrollSpeed: 1.45,
      zIndex: 48,
      ritual: 'bean',
    },
    {
      id: 'bean-2',
      src: '/assets/coffee/bean.png',
      alt: 'Roasted coffee bean',
      x: 86,
      y: 26,
      width: 58,
      depth: 1.1,
      rotate: 30,
      floatDuration: 9,
      floatDelay: 0.8,
      floatAmplitude: 24,
      floatAmplitudeX: 10,
      floatRotate: -12,
      scrollSpeed: 1.3,
      zIndex: 46,
      ritual: 'bean',
      hideOnMobile: true,
    },
    {
      id: 'bean-3',
      src: '/assets/coffee/bean.png',
      alt: 'Roasted coffee bean',
      x: 90,
      y: 58,
      width: 64,
      depth: 1.4,
      rotate: 12,
      floatDuration: 6.1,
      floatDelay: 0.4,
      floatAmplitude: 18,
      floatAmplitudeX: 14,
      floatRotate: 14,
      scrollSpeed: 1.6,
      zIndex: 50,
      ritual: 'bean',
      hideOnTablet: true,
    },
    {
      id: 'ice-1',
      src: '/assets/coffee/ice.png',
      alt: 'Ice cube',
      x: 22,
      y: 16,
      width: 90,
      depth: 1.3,
      rotate: -16,
      floatDuration: 8.4,
      floatDelay: 0.6,
      floatAmplitude: 14,
      floatAmplitudeX: 8,
      floatRotate: 8,
      scrollSpeed: 1.5,
      zIndex: 54,
      ritual: 'ice',
    },
    {
      id: 'ice-2',
      src: '/assets/coffee/ice.png',
      alt: 'Ice cube',
      x: 78,
      y: 14,
      width: 74,
      depth: 1.2,
      rotate: 22,
      floatDuration: 7.8,
      floatDelay: 1.2,
      floatAmplitude: 16,
      floatAmplitudeX: 10,
      floatRotate: -10,
      scrollSpeed: 1.55,
      zIndex: 53,
      ritual: 'ice',
      hideOnMobile: true,
    },
    {
      id: 'sugar-1',
      src: '/assets/coffee/sugar.png',
      alt: 'Sugar cube',
      x: 18,
      y: 52,
      width: 66,
      depth: 1.15,
      rotate: 18,
      floatDuration: 10,
      floatDelay: 0.9,
      floatAmplitude: 12,
      floatAmplitudeX: 7,
      floatRotate: 6,
      scrollSpeed: 1.2,
      zIndex: 47,
      ritual: 'sugar',
    },
    {
      id: 'sugar-2',
      src: '/assets/coffee/sugar.png',
      alt: 'Sugar cube',
      x: 82,
      y: 50,
      width: 58,
      depth: 1.08,
      rotate: -10,
      floatDuration: 11.2,
      floatDelay: 1.7,
      floatAmplitude: 10,
      floatAmplitudeX: 6,
      floatRotate: -5,
      scrollSpeed: 1.15,
      zIndex: 45,
      ritual: 'sugar',
      hideOnTablet: true,
    },
    {
      id: 'leaf-1',
      src: '/assets/coffee/leaf.png',
      alt: 'Coffee leaf',
      x: 8,
      y: 42,
      width: 110,
      depth: 0.75,
      rotate: -28,
      floatDuration: 12,
      floatDelay: 0.4,
      floatAmplitude: 12,
      floatAmplitudeX: 5,
      floatRotate: 5,
      scrollSpeed: 0.75,
      zIndex: 30,
      ritual: 'decor',
      hideOnMobile: true,
    },
  ],
  particles: {
    count: 36,
    colors: ['#E8B07A', '#F3D5B5', '#FFFFFF', '#C4895A'],
  },
  smoke: {
    enabled: true,
    color: 'rgba(255, 236, 214, 0.3)',
  },
  ritualSteps: [
    'Steam rises',
    'Milk flows in',
    'Ice cubes drop',
    'Sugar dissolves',
    'Coffee beans float',
  ],
}
