import type { ThemeConfig } from '@/types/hero'

export const coffeeTheme: ThemeConfig = {
  id: 'coffee',
  name: 'Aroma Atelier',
  tagline: 'Luxury coffee brand experience',
  nav: {
    logo: 'AROMA',
    links: ['Blend', 'Origin', 'Ritual', 'Journal'],
    cta: 'Order Reserve',
  },
  headline: {
    line1: 'Crafted for',
    line2: 'quiet mornings',
    accent: 'quiet mornings',
  },
  subheadline:
    'A cinematic product stage where your hero roast floats out of the page — warm, tactile, unforgettable.',
  buttons: [
    { label: 'Explore the Blend', variant: 'primary' },
    { label: 'Watch the Ritual', variant: 'secondary' },
  ],
  colors: {
    bgFrom: '#1A100C',
    bgVia: '#3A2418',
    bgTo: '#120C09',
    accent: '#E8B07A',
    accentSoft: '#C4895A',
    text: '#F7EFE6',
    textMuted: 'rgba(247, 239, 230, 0.68)',
    glow: 'rgba(232, 176, 122, 0.35)',
    vignette: 'rgba(8, 4, 2, 0.72)',
    particle: ['#E8B07A', '#F3D5B5', '#FFFFFF', '#C4895A'],
    smoke: 'rgba(255, 236, 214, 0.22)',
  },
  mockup: {
    title: 'Aroma Reserve',
    subtitle: 'Single-origin experience',
    browserUrl: 'aroma.atelier/reserve',
  },
  product: {
    src: '/assets/coffee/cup.svg',
    alt: 'Signature ceramic cup of specialty coffee',
    width: 340,
  },
  floatingObjects: [
    {
      id: 'bean-1',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 14,
      y: 28,
      width: 54,
      depth: 1.15,
      rotate: -18,
      floatDuration: 7.5,
      floatDelay: 0.2,
      floatAmplitude: 18,
      floatAmplitudeX: 10,
      floatRotate: 8,
      scrollSpeed: 1.35,
      zIndex: 40,
    },
    {
      id: 'bean-2',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 78,
      y: 24,
      width: 42,
      depth: 0.95,
      rotate: 24,
      floatDuration: 9.2,
      floatDelay: 1.1,
      floatAmplitude: 22,
      floatAmplitudeX: 8,
      floatRotate: -10,
      scrollSpeed: 1.2,
      zIndex: 38,
      hideOnMobile: true,
    },
    {
      id: 'bean-3',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 84,
      y: 62,
      width: 48,
      depth: 1.3,
      rotate: 8,
      floatDuration: 6.4,
      floatDelay: 0.6,
      floatAmplitude: 16,
      floatAmplitudeX: 12,
      floatRotate: 12,
      scrollSpeed: 1.55,
      zIndex: 42,
      hideOnTablet: true,
    },
    {
      id: 'leaf-1',
      src: '/assets/coffee/leaf.svg',
      alt: 'Coffee leaf',
      x: 10,
      y: 58,
      width: 90,
      depth: 0.85,
      rotate: -28,
      floatDuration: 11,
      floatDelay: 0.4,
      floatAmplitude: 14,
      floatAmplitudeX: 6,
      floatRotate: 6,
      scrollSpeed: 0.95,
      zIndex: 34,
      hideOnMobile: true,
    },
    {
      id: 'bag-1',
      src: '/assets/coffee/bag.svg',
      alt: 'Coffee bag',
      x: 76,
      y: 70,
      width: 110,
      depth: 0.7,
      rotate: 12,
      floatDuration: 10.5,
      floatDelay: 1.8,
      floatAmplitude: 12,
      floatAmplitudeX: 5,
      floatRotate: -4,
      scrollSpeed: 0.8,
      zIndex: 30,
      hideOnTablet: true,
    },
    {
      id: 'bean-4',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 22,
      y: 72,
      width: 36,
      depth: 1.4,
      rotate: -8,
      floatDuration: 5.8,
      floatDelay: 2.2,
      floatAmplitude: 20,
      floatAmplitudeX: 14,
      floatRotate: 14,
      scrollSpeed: 1.65,
      zIndex: 44,
      hideOnMobile: true,
    },
  ],
  particles: {
    count: 28,
    colors: ['#E8B07A', '#F3D5B5', '#FFFFFF', '#C4895A'],
  },
  smoke: {
    enabled: true,
    color: 'rgba(255, 236, 214, 0.22)',
  },
}
