import type { ThemeConfig } from '@/types/hero'

export const coffeeTheme: ThemeConfig = {
  id: 'coffee',
  name: 'Aroma Atelier',
  tagline: 'A coffee website that feels warm before you even visit',
  layout: 'cinematic',
  nav: {
    logo: 'AROMA',
    links: ['Blend', 'Origin', 'Ritual', 'Journal'],
    cta: 'Order Reserve',
  },
  headline: {
    line1: 'Warm before',
    line2: 'the first sip',
    accent: 'the first sip',
  },
  subheadline:
    'Scroll-based parallax brings the cup to life — steam rises, milk flows, ice drops, sugar dissolves, beans float.',
  buttons: [
    { label: 'Taste the Ritual', variant: 'primary' },
    { label: 'Explore the Blend', variant: 'secondary' },
  ],
  colors: {
    bgFrom: '#140C08',
    bgVia: '#3B2418',
    bgTo: '#0C0806',
    accent: '#E8B07A',
    accentSoft: '#C4895A',
    text: '#F7EFE6',
    textMuted: 'rgba(247, 239, 230, 0.68)',
    glow: 'rgba(232, 176, 122, 0.42)',
    vignette: 'rgba(6, 3, 1, 0.78)',
    particle: ['#E8B07A', '#F3D5B5', '#FFFFFF', '#C4895A'],
    smoke: 'rgba(255, 236, 214, 0.28)',
  },
  mockup: {
    title: 'Morning Ritual',
    subtitle: 'Single-origin pour, crafted slow',
    browserUrl: 'aroma.atelier/ritual',
  },
  product: {
    src: '/assets/coffee/cup.svg',
    alt: 'Signature ceramic cup of specialty coffee',
    width: 460,
  },
  floatingObjects: [
    {
      id: 'bean-1',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 18,
      y: 30,
      width: 58,
      depth: 1.2,
      rotate: -22,
      floatDuration: 7.2,
      floatDelay: 0.15,
      floatAmplitude: 20,
      floatAmplitudeX: 12,
      floatRotate: 10,
      scrollSpeed: 1.45,
      zIndex: 48,
      ritual: 'bean',
    },
    {
      id: 'bean-2',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 80,
      y: 26,
      width: 46,
      depth: 1.05,
      rotate: 28,
      floatDuration: 9,
      floatDelay: 0.8,
      floatAmplitude: 24,
      floatAmplitudeX: 10,
      floatRotate: -12,
      scrollSpeed: 1.3,
      zIndex: 46,
      ritual: 'bean',
      hideOnMobile: true,
    },
    {
      id: 'bean-3',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 86,
      y: 58,
      width: 52,
      depth: 1.35,
      rotate: 10,
      floatDuration: 6.1,
      floatDelay: 0.4,
      floatAmplitude: 18,
      floatAmplitudeX: 14,
      floatRotate: 14,
      scrollSpeed: 1.6,
      zIndex: 50,
      ritual: 'bean',
      hideOnTablet: true,
    },
    {
      id: 'bean-4',
      src: '/assets/coffee/bean.svg',
      alt: 'Coffee bean',
      x: 14,
      y: 64,
      width: 40,
      depth: 1.4,
      rotate: -12,
      floatDuration: 5.6,
      floatDelay: 1.5,
      floatAmplitude: 22,
      floatAmplitudeX: 16,
      floatRotate: 16,
      scrollSpeed: 1.7,
      zIndex: 52,
      ritual: 'bean',
      hideOnMobile: true,
    },
    {
      id: 'ice-1',
      src: '/assets/coffee/ice.svg',
      alt: 'Ice cube',
      x: 30,
      y: 16,
      width: 70,
      depth: 1.25,
      rotate: -14,
      floatDuration: 8.4,
      floatDelay: 0.6,
      floatAmplitude: 14,
      floatAmplitudeX: 8,
      floatRotate: 8,
      scrollSpeed: 1.5,
      zIndex: 54,
      ritual: 'ice',
    },
    {
      id: 'ice-2',
      src: '/assets/coffee/ice.svg',
      alt: 'Ice cube',
      x: 70,
      y: 12,
      width: 56,
      depth: 1.15,
      rotate: 20,
      floatDuration: 7.8,
      floatDelay: 1.2,
      floatAmplitude: 16,
      floatAmplitudeX: 10,
      floatRotate: -10,
      scrollSpeed: 1.55,
      zIndex: 53,
      ritual: 'ice',
      hideOnMobile: true,
    },
    {
      id: 'sugar-1',
      src: '/assets/coffee/sugar.svg',
      alt: 'Sugar cube',
      x: 24,
      y: 48,
      width: 54,
      depth: 1.1,
      rotate: 18,
      floatDuration: 10,
      floatDelay: 0.9,
      floatAmplitude: 12,
      floatAmplitudeX: 7,
      floatRotate: 6,
      scrollSpeed: 1.2,
      zIndex: 47,
      ritual: 'sugar',
    },
    {
      id: 'sugar-2',
      src: '/assets/coffee/sugar.svg',
      alt: 'Sugar cube',
      x: 76,
      y: 46,
      width: 48,
      depth: 1.05,
      rotate: -10,
      floatDuration: 11.2,
      floatDelay: 1.7,
      floatAmplitude: 10,
      floatAmplitudeX: 6,
      floatRotate: -5,
      scrollSpeed: 1.15,
      zIndex: 45,
      ritual: 'sugar',
      hideOnTablet: true,
    },
    {
      id: 'milk-1',
      src: '/assets/coffee/milk.svg',
      alt: 'Milk pour',
      x: 62,
      y: 34,
      width: 120,
      depth: 0.95,
      rotate: -8,
      floatDuration: 8.8,
      floatDelay: 0.3,
      floatAmplitude: 10,
      floatAmplitudeX: 4,
      floatRotate: 3,
      scrollSpeed: 1.1,
      zIndex: 49,
      ritual: 'milk',
      hideOnMobile: true,
    },
    {
      id: 'splash-1',
      src: '/assets/coffee/splash.svg',
      alt: 'Milk splash',
      x: 50,
      y: 58,
      width: 160,
      depth: 0.85,
      rotate: 0,
      floatDuration: 9.5,
      floatDelay: 0.5,
      floatAmplitude: 8,
      floatAmplitudeX: 4,
      scrollSpeed: 0.9,
      zIndex: 44,
      ritual: 'splash',
      hideOnMobile: true,
    },
    {
      id: 'leaf-1',
      src: '/assets/coffee/leaf.svg',
      alt: 'Coffee leaf',
      x: 10,
      y: 42,
      width: 96,
      depth: 0.7,
      rotate: -30,
      floatDuration: 12,
      floatDelay: 0.4,
      floatAmplitude: 12,
      floatAmplitudeX: 5,
      floatRotate: 5,
      scrollSpeed: 0.75,
      zIndex: 30,
      ritual: 'decor',
      hideOnMobile: true,
    },
  ],
  particles: {
    count: 36,
    colors: ['#E8B07A', '#F3D5B5', '#FFFFFF', '#C4895A'],
  },
  smoke: {
    enabled: true,
    color: 'rgba(255, 236, 214, 0.3)',
  },
  ritualSteps: [
    'Steam rises',
    'Milk flows in',
    'Ice cubes drop',
    'Sugar dissolves',
    'Coffee beans float',
  ],
}
